/*
* Author: Diep Vo
*
* Please be aware that this file was generated by 'flutter gen-l10n'.
* However, note that 'flutter gen-l10n' is not compatible with
* Flutter packages and only works with Flutter applications.
* Hence, I manually copied this code to the source folder.
* We plan to gradually add translatable strings to this file over time.
* */

import 'package:intl/intl.dart';

import 'payment_gate_localizations.dart';

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get paymentMethod => "Payment method";

  @override
  String get cashOnDelivery => "Cash on delivery (COD)";

  @override
  String get bankTransfer => "Online banking & Direct debit";

  @override
  String get creditCard => "Credit card";

  @override
  String get crypto => "Crypto";

}
