List<String> productSearchList = [
  'TravelPro Rolling Luggage',
  'Adventure Seeker Backpack',
  'Wanderlust Duffel Bag',
  'Nomad Travel Pillow',
  'Expedition Camping Tent',
  'Explore More Hiking Boots',
  'Jetsetter Suitcase Set',
  'Trekker\'s Backpacking Gear',
  'Roaming Travel Adapter',
  'Globetrotter Travel Planner',
  'Urban Explorer Daypack',
  'Voyager Packing Cubes',
  'Discoverer Adventure Hat',
  'Sightseer Binoculars',
  'Road Trip Essentials Kit',
  'Adventurer\'s First Aid Kit',
  'Trekking Pole Set',
  'Island Hopper Hammock',
  'Traveler\'s Toiletry Bag',
  'Camper\'s Portable Stove',
];
