/*
* Author: Diep Vo
*
* Please be aware that this file was generated by 'flutter gen-l10n'.
* However, note that 'flutter gen-l10n' is not compatible with
* Flutter packages and only works with Flutter applications.
* Hence, I manually copied this code to the source folder.
* We plan to gradually add translatable strings to this file over time.
* */

import 'shared_localizations.dart';

/// The translations for English (`en`).
class SharedLocalizationsEn extends SharedLocalizations {
  SharedLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get welcomeToEcommerce => "Welcome to eCommerce";

  @override
  String helloUser(String userName) {
    return "Hello $userName";
  }

  @override
  String userHaveNApple(String userName, int appleCount) {
    return plural(appleCount,
        zero: "$userName doesn't have any apples.",
        one: "$userName has 1 apple",
        other: (count) => "$userName has $count apples");
  }

  @override
  String heOrSheDidIt(String sex) {
    return select(sex,
        {"male": "He did it", "female": "She did it", "other": "They did it"});
  }

  @override
  String get searchForProvince => "Search for province";

  @override
  String get noResultsFound => "No results found";

  @override
  String get someFamousLocations => "Some famous locations";

  @override
  String get locationsNearYou => "Around you";

  @override
  String characters(int current, int limit) {
    return plural(current,
        other: (count) => "$current/$limit characters",
        one: "$current/$limit character",
        zero: "$current/$limit characters");
  }

  @override
  String get dataNotFound => "Data not found";

  @override
  String get error => "Error";

  @override
  String get ok => "OK";

  @override
  String nProduct(int count) => plural(count,
      other: (count) => "$count Products",
      one: "1 Product",
      zero: "0 Products");

  @override
  String get customerReviews => "Customer Reviews";

  @override
  String nReview(num count) => plural(count,
      other: (count) => "$count Reviews", one: "1 Review", zero: "0 Reviews");

  @override
  String get size => "Size";

  @override
  String get color => "Color";

  @override
  String get helpful => "Helpful";

  @override
  String get report => "Report";

  @override
  String get claim => "Claim";

  @override
  String get voucher => "Voucher";

  @override
  String pagination(String currentPage, String limitPage) {
    return "Page $currentPage of $limitPage";
  }

  @override
  String searchResults(int total, String? category, String? label) {
    String res = "${compact(total)} result ";
    if (category != null) {
      res = "$res for $category ";
    }
    if (label != null) {
      res = "$res in $label ";
    }
    return res;
  }

  @override
  String get allProduct => "All Product";

  @override
  String voucherDiscount(String name) {
    return "Voucher discount $name";
  }

  @override
  String minSentVoucher(String value) {
    return "Min spend $value";
  }

  @override
  String validVoucher(String ranger) {
    return "Valid until $ranger";
  }

  @override
  String get follow => "Follow";

  @override
  String get chat => "Chat";

  @override
  String get viewAll => "View all";

  @override
  String get popularItemInThisSeason => "Popular Item in this season";

  @override
  String get dealUnder => "Deal Under";

  @override
  String get purchaseHistory => "My order";

  @override
  String get apply => "Apply";

  @override
  String get brand => "Brand";

  @override
  String get condition => "Condition";

  @override
  String get filter => "Filter";

  @override
  String get goToCart => "Go to Cart";

  @override
  String get productCategory => "Product Category";

  @override
  String get rating => "Rating";

  @override
  String get region => "Region";

  @override
  String get reset => "Reset";

  @override
  String get searchSuggestion => "Search Suggestion:";

  @override
  String get shipmentMethod => "Shipment Method";

  @override
  String get sort => "Sort";

  @override
  String get priceRange => "Price Range";

  @override
  String get seeLess => "See Less";

  @override
  String get seeMore => "See More";

  @override
  String get all => "All";

  @override
  String get cosmetic => "Cosmetic";

  @override
  String get fashion => "Fashion";

  @override
  String searchResult(int start, int end, int total, String category) {
    return "${compact(start)} - ${compact(end)}  of ${compact(total)} results for $category";
  }

  @override
  String get menu => "Menu";

  @override
  String get cart => "Cart";

  @override
  String get item => "Items";

  @override
  String get myCart => "My Cart";

  @override
  String get myOrder => "My Order";

  @override
  String get home => "Home";

  @override
  String get addressDefault => "Default";

  @override
  String get office => "Office";

  @override
  String get addNewAddress => "Add new address";

  @override
  String get cancel => "Cancel";

  @override
  String get address => "Address";

  @override
  String get addressType => "Address type";

  @override
  String get city => "City";

  @override
  String get deleteAddress => "Delete address";

  @override
  String get district => "District";

  @override
  String get fullName => "Full name";

  @override
  String get phoneNumber => "Phone number";

  @override
  String get setAsDefaultAddress => "Set as default address";

  @override
  String get ward => "Ward";

  @override
  String get streetName => "Street name";

  @override
  String get checkout => "Checkout";

  @override
  String get total => "Total";

  @override
  String variation(String value) {
    return "Variation: $value";
  }

  String get allProducts => "All products";

  @override
  String get visitShop => "Visit shop";

  @override
  String get shopVouchers => "Shop vouchers";

  @override
  String get vouchers => "Vouchers";

  @override
  String get selectVouchers => "Select vouchers";

  @override
  String get paymentMethod => "Payment method";

  @override
  String get cod => "Cash on delivery (COD)";

  @override
  String get onlineBanking => "Online banking & Direct debit";

  @override
  String get paypal => "Paypal";

  @override
  String get creditCard => "Credit card";

  @override
  String get paymentDetails => "Payment details";

  @override
  String get subtotal => "Subtotal";

  @override
  String get discounts => "Discounts";

  @override
  String get deliveryFee => "Delivery fee";

  String get buyNow => "Buy Now";

  @override
  String cartShowNumberItems(int number) {
    return plural(number,
        other: (number) => "Cart: $number items",
        one: "Cart: 1 item",
        zero: "Cart: 0 items");
  }

  @override
  String get changeEmailAddress => "Change email address";

  @override
  String get description => "Description";

  @override
  String get flashSale => "Flash Sale";

  @override
  String get freeReturnWithin7Days => "Free return within 7 days";

  @override
  String get freeShipping => "Free Ship";

  @override
  String freeShippingOnOrderFrom(cost, currencyName) =>
      "Free shipping on orders from ${simpleCurrency(cost, name: currencyName)}";

  @override
  String get productInformation => "Product Information";

  @override
  String get quantity => "Quantity";

  @override
  String get returnGoods => "Return Goods";

  @override
  String get stock => "Stock";

  @override
  String get addToCart => "Add to Cart";

  @override
  String get customerReview => "Customer Review";

  @override
  String get follower => "Follower";

  @override
  String get product => "Product";

  @override
  String get reviews => "Reviews";

  @override
  String get Select => "Select";

  @override
  String get addressList => "Address List";

  @override
  String get cancelled => "Cancelled";

  @override
  String get car => "Car";

  @override
  String get checkOut => "Checkout";

  @override
  String get flightTicket => "Flight Ticket";

  @override
  String get food => "Food";

  @override
  String get helpCenter => "Help Center";

  @override
  String get homePage => "Home Page";

  @override
  String get hotel => "Hotel";

  @override
  String get logOut => "Logout";

  @override
  String get manage => "Manage";

  @override
  String get myShop => "My Shop";

  @override
  String get productDetails => "Product Details";

  @override
  String get purchasing => "Purchasing";

  @override
  String get securityCenter => "Security Center";

  @override
  String get settings => "Settings";

  @override
  String get tour => "Tour";

  @override
  String nItem(int count) => plural(count,
      other: (count) => "$count Items", one: "1 Item", zero: "0 Items");

  @override
  String priceCheckOut(cost, currencyName) =>
      simpleCurrency(cost, name: currencyName);

  @override
  String get datanotfound => "Data is not found. Please try again later.";

  @override
  String get categoryList => "Category List";

  @override
  String get confirm => "Confirm";

  @override
  String get viewMore => "View more";

  @override
  String get shippingVouchers => "Shipping Vouchers";

  @override
  String discountVoucher(String value) {
    return "Discount $value%";
  }

  @override
  String expiredDayVoucher(String ranger) {
    return "Expired Day: $ranger";
  }

  @override
  String minSpendVoucher(cost, currencyName) =>
      "Min spend ${simpleCurrency(cost, name: currencyName)}";

  @override
  String freeShipVoucher(cost, currencyName) =>
      "Freeship ${simpleCurrency(cost, name: currencyName)}";

  @override
  String addToCartSuccessfully(String productName) {
    return "Added $productName to cart successfully.";
  }

  @override
  String get noItem => "No Item";

  @override
  String get statusCancel => "Cancelled";

  @override
  String get statusPaymentFailed => "Payment failed";

  @override
  String get statusPaymentSuccessfully => "Payment successfully";

  @override
  String get statusDelivering => "Delivering";

  @override
  String get statusDelivered => "Delivered";

  @override
  String get statusCompleted => "Completed";

  @override
  String get statusRefund => "Refund";

  @override
  String get orderTotal => "Order Total";

  @override
  String get reOrder => "Re-order";

  @override
  String get rePay => "Re-pay";

  @override
  String get cancelOrder => "Cancel order";

  @override
  String get refundOrder => "Refund Order";

  @override
  String get receivedOrder => "Received order";

  @override
  String get toPay => "To pay";

  @override
  String get toShip => "To ship";

  @override
  String get toDelivery => "To delivery";

  @override
  String get deliveredMyOrder => "Delivered";

  @override
  String get completedMyOrder => "Completed";

  @override
  String get cancelMyOrder => "Cancel";

  @override
  String get refundMyOrder => "Refund";

  @override
  String get noData => "Not Found Data";

  @override
  String get more => "More";

  @override
  String get goodQuality => "Good Quality";

  @override
  String get withinMedias => "Within Medias";

  @override
  String get withinComments => "Within Comments";

  @override
  String get fastDelivery => "Fast Delivery";

  @override
  String get carefulPacking => "Careful Packing";

  @override
  String get reasonablePrices => "Reasonable prices";

  @override
  String get goodAttitude => "Good attitude";

  @override
  String get loading => "Loading...";

  @override
  String get confirmDeleteAddress => "Do you want to delete the address?";

  @override
  String get save => "Save";

  @override
  String get create => "Create";

  @override
  String get editAddress => "Edit address";

  @override
  String get rateTheProducts => "Rate the products";

  @override
  String get photoVideo => "Photo/video";

  @override
  String get giveUsYourFeedback => "Give us your feedback";

  @override
  String get textPlaceHolderFeedback => "What do you think about this product?";

  @override
  String get questionFeedback =>
      "What do you like most? Please share it with Soctrip now.";

  @override
  String get questionRateStar => "How was your experience with this product?";

  @override
  String get submit => "Submit";

  @override
  String get variationProduct => "Variation";

  @override
  String checkoutGetItem(int total) {
    return "Check out($total)";
  }

  @override
  String get no => "No";

  @override
  String get yes => "Yes";

  @override
  String get titleDeleteItem => "Delete Product";

  @override
  String get descriptionDeleteItem =>
      "Are you sure want to delete this product?";

  @override
  String get orderManagement => "Order Management";

  @override
  String get productCategories => "Product Categories";

  @override
  String get sellerChannel => "Seller Channel";

  @override
  String get shopAnalytics => "Shop Analytics";

  @override
  String get modifyCategoryHint =>
      'Choose the right category type to make your product more appealing. This ensures it is listed in the most relevant and eye-catching section of the marketplace, helping you reach your target audience more effectively.';

  @override
  String get addCategory => "Add Category";

  @override
  String get addProduct => "Add Product";

  @override
  String get addSubCategory => "Add Sub Category";

  @override
  String get categoryDeleted => "Category deleted.";

  @override
  String get categoryPublished => "Category published.";

  @override
  String get categoryUpdated => "Category updated.";

  @override
  String get delete => "Delete";

  @override
  String get edit => "Edit";

  @override
  String get editCategory => "Edit Category";

  @override
  String get noCategoryFound => "No category found";

  @override
  String get noCategoryFoundHint =>
      'Your shop will automatically display the category generated by the system. You can also add new custom Collections';

  @override
  String get selectCategoryType => "Select Category Type";

  @override
  String get categoryAdded => "Category added.";

  @override
  String get categoryName => "Category name";

  @override
  String get categoryType => "Category type";

  @override
  String get enterCategoryName => "Enter category name";

  @override
  String get selectType => "Select type";

  @override
  String get choose => "Choose";

  @override
  String get deleteCategory => "Delete category";

  @override
  String get deleteCategoryHint =>
      "If you delete a category, all sub-Collections under it will also be deleted. Are you sure you want to delete Summer Collection?";

  @override
  String get addCategories => "Add categories";

  @override
  String get addSubCategories => "Add sub categories";

  @override
  String get editCategories => "Edit categories";

  @override
  String get changeDefaultAddress => "Change Default Address";

  @override
  String get confirmDefaultAddress => "Do you want change default address?";

  @override
  String get country => "Country";

  @override
  String get warningChooseProduct => "Please choose product";

  @override
  String get checkoutSuccess => "Thank you for your order!";

  @override
  String get checkoutFail => "Failed payment!";

  @override
  String get orderID => "Order ID";

  @override
  String get transactionDate => "Transaction Date";

  @override
  String get trackOrder => "Track Order";

  @override
  String get continueShopping => "Continue shopping";

  @override
  String get titleThanksRate => "Thanks for your ratings!";

  @override
  String get contentThanksRate => "Thank you for your review of the product.";

  @override
  String get close => "Close";

  @override
  String get good => "Good";

  @override
  String get search => "Search";

  @override
  String get searchInShop => "Search in this shop";

  @override
  String get noProductFound => "No Product found";

  @override
  String get inStockWithColon => "In Stock: ";

  @override
  String get priceWithColon => "Price: ";

  @override
  String get categoryEdited => "Category edited.";

  @override
  String get categoryUnpublished => "Category unpublished.";

  @override
  String get errorDelete => "Please delete child catalog first.";

  @override
  String get plsSelectOptionToBuy => "Please select option to buy";

  @override
  String get addNewProduct => "Add new product";

  @override
  String get addOption => "Add option";

  @override
  String get addVariant => "Add variant";

  @override
  String get attribute => "Attribute";

  @override
  String get category => "Category";

  @override
  String get generalInformation => "General information";

  @override
  String get inStock => "In stock";

  @override
  String get newAttribute => "New attribute";

  @override
  String get options => "Options";

  @override
  String get price => "Price";

  @override
  String get pricing => "Pricing";

  @override
  String get productDescription => "Product description";

  @override
  String get productDetail => "Product detail";

  @override
  String get productName => "Product Name";

  @override
  String get publish => "Publish";

  @override
  String get recommendedForImage =>
      "Recommended image ratios for uploads are 3:4 or 1:1.";

  @override
  String get salePrice => "Sale Price";

  @override
  String get selectImage => "Select Image";

  @override
  String get settingVariantPrices => "Setting variant prices";

  @override
  String get settingVariation => "Setting variation";

  @override
  String get tags => "Tags";

  @override
  String get totalUploadedImages => "Total uploaded images:";

  @override
  String get value => "Value";

  @override
  String get variantName => "Variant name";

  @override
  String get variants => "Variants";

  @override
  String get setAsDraft => "Set as draft";

  @override
  String get addNewAttribute => "Add new attribute";

  @override
  String get updateAttribute => "Update Attribute";

  @override
  String get selects => "selects";

  @override
  String get applyForAll => "Apply for all variants";

  @override
  String get dateFormatForCalendar => "MM/dd/yyyy";

  @override
  String get nothingIsSelected => "Nothing is selected";

  @override
  String get active => "Active";

  @override
  String get draft => "Draft";

  @override
  String get outOfStock => "Out Of Stock";

  @override
  String get max => "Max";

  @override
  String get min => "Min";

  @override
  String get confirmDeleteProduct => "Do you want to delete the product";

  @override
  String get deleteProduct => "Delete Product";

  @override
  String get confirmSetAsProduct => "Do you want to set as draft the product";

  @override
  String get valueException => "Value exception";

  @override
  String get nothingImageSelect => "Nothing is selected";

  @override
  String get notData => "Not data!";

  @override
  String get orderDetail => "Order Details";

  @override
  String get orderInfo => "Order Information";

  @override
  String get orderId => "Order ID";

  @override
  String get status => "Status";

  @override
  String get orderDate => "Order Date";

  @override
  String get note => "Note";

  @override
  String get name => "Name";

  @override
  String get deliveryInfo => "Delivery Information";

  @override
  String get orderStatus => "Order Status";

  @override
  String get orderStatusNote => "Order Status Note";

  @override
  String get orderStatusDetail => "Order Status Detail";

  @override
  String get productList => "Product List";

  @override
  String get paymentInformation => "Payment Information";

  @override
  String get subStatus => "Substatus";

  @override
  String get messageForCustomer => "Message For Customer";

  @override
  String get textPlaceHolderOrderManagement => "Write your message here...";

  @override
  String get descriptionMessage =>
      "User will be received this message (included Order details URL) through Soctrip chatbox. ";

  @override
  String get clickToUpload => "Click to upload";

  @override
  String get cancelReason => "Cancel Reason";

  @override
  String get descriptionUpload => "SVG, PNG, JPG or GIF (max. 800x400px)";

  @override
  String get attachments => "Attachments";

  @override
  String get chooseReason => "Choose cancel reason";

  @override
  String get inputNote => "Input Note";

  @override
  String get chooseSubStatus => "Choose SubStatus";

  @override
  String get pleaseChooseStatusFirst => "Please choose status first";

  @override
  String get descriptionAttachmentOne =>
      "Send update to user \nUser will receive a notification about this order status on Soctrip and their email.";

  @override
  String get descriptionAttachmentTwo =>
      "Show this step for user \nUser can see this step in “Order Details”.";

  @override
  String get updateStatus => "Update Status";

  @override
  String get descriptionCancelOrder =>
      "Please select a cancellation reason. Take note this will cancel all items in the order and the action cannot be undone";

  @override
  String get reviewRating => "Review Rating";

  @override
  String get datetimeFormatForCalendar => "MM/dd/yyyy • HH:mm";

  @override
  String get favorite => "Favorite";

  @override
  String get shopping => "Shopping";

  @override
  String get yourMarket => "Your Market";

  @override
  String get closing => "Closing";

  @override
  String get opening => "Opening";

  @override
  String get viewLess => "View less";

  @override
  String get searchProduct => "Search product";

  @override
  String get selectAll => "Select all";

  @override
  String get applicableProduct => "Applicable product";

  @override
  String get basicInformation => "Basic information";

  @override
  String get discountType => "Discount type";

  @override
  String get maxDistributionPerBuyer => "Max distribution per buyer";

  @override
  String get maximumDiscountPrice => "Maximum discount price";

  @override
  String get minimumOrderPrice => "Minimum order price";

  @override
  String get platform => "Platform";

  @override
  String get special => "Special";

  @override
  String get validPeriod => "Valid period";

  @override
  String get voucherCode => "Voucher code";

  @override
  String get voucherDisplaySettings => "Voucher display settings";

  @override
  String get voucherName => "Voucher name";

  @override
  String get voucherSettings => "Voucher settings";

  @override
  String get voucherDetail => "Voucher detail";

  @override
  String get voucherType => "Voucher type";

  @override
  String get plsGoToWeb => "Please visit website to use this feature";

  @override
  String get shopBuilder => "Shop builder";

  @override
  String get voucherManagement => "Marketing";

  @override
  String get addNewVoucher => "Add new voucher";

  @override
  String get plsInputAlphabet =>
      "Please input only alphabetical characters (A-Z) and numbers (0-9), with a maximum length of 5 characters.";

  @override
  String get kindlyFurnishVoucherDetails => 'Kindly furnish essential voucher details. All fields are mandatory.';

  @override
  String get plsConfigVoucherReward => "Please configure all voucher reward parameters. This is the key feature of the voucher";
  
  @override
  String get byPercentage => "By Percentage";
  
  @override
  String get chooseYourPaymentMethod => "Choose your payment method";
  
  @override
  String get chooseYourPlatform => "Choose your platform";
  
  @override
  String get chooseYourVoucherType => "Choose your voucher type";
  
  @override
  String get enhanceYourCustomerUnderstanding => "Enhance your customers' understanding of the voucher you're issuing.";
  
  @override
  String get fixAmount => "Fix amount";
  
  @override
  String get inputDescriptionHere => "Input description here";
  
  @override
  String get inputHere => "Input here";
  
  @override
  String get inputVoucherName => "Input voucher name";
  
  @override
  String get inputYourVoucherCode => "Input your voucher code";
  
  @override
  String get noExpiryDate => "No expired date";
  
  @override
  String get preview => "Preview";
  
  @override
  String get automaticallyDisplayOnHomePage => 'The voucher will be automatically displayed on shop homepage, product page, shopping cart page and also can be shared on Soctrip Merchant Live.';
  
  @override
  String get displayOnAllPages => "Display on all pages";
  
  @override
  String get informCustomerDemographic => "Please inform us about the customer demographic you intend to target with the voucher issuance.";
  
  @override
  String get specificProducts => "Specific products";
  
  @override
  String get toBeSharedThroughVoucherCode => "To be shared through voucher code";
  
  @override
  String get onlySharableViaVoucherCode => "Shop vouchers that are only sharable via voucher code will be saved as private voucher";
  
  @override
  String get selectVoucherType => "Select voucher type";

  @override
  String get exclusivelyVisibleDuringLiveStream => 'This voucher is exclusively visible during livestream views, and only livestream viewers have access to it.';

  @override
  String get onlyDisplayOnLiveStream => 'Only display on livestream view';

  @override
  String get voucherPreview => "Preview voucher";

  @override
  String get reward => "Reward";

  @override
  String get targetBuyer => "Target buyer";

  @override
  String get limitedRedemption => "Limited redemption";

  @override
  String getAVoucher(cost, currencyName){
    return "Get a ${currencyName == "%" ? "$cost%" : simpleCurrency(cost, name: currencyName)} off";
  }

  @override
  String minimumOrderPrices(cost, currencyName){
    return "Minimum order prices: ${currencyName == "%" ? "$cost%" : simpleCurrency(cost, name: currencyName)}";
  }

  @override
  String get addVoucher => "Add voucher";

  @override
  String get setAmount => "Set amount";

  @override
  String get noLimit => "No limit";
  
  @override
  String get allPlatforms => "All platforms";
  
  @override
  String get app => "Mobile App";
  
  @override
  String get web => "Websites";

  @override
  String get required => "required";

  @override
  String get selectPlatform => "Select platform";

  @override
  String get plsInputAllOptions => "Please input all required fields to create voucher";

  @override
  String get createPost => "Create Post";

  @override
  String hintCreatePost(String content) {
    return "Hi $content, Share your feelings!";
  }

  @override
  String get post => "Post";

  @override
  String get private => "Private";

  @override
  String get public => "Public";

  @override
  String get shareToFeedSuccess => "Share Successfully";

  @override
  String get myRestaurant => "My Restaurant";

  @override
  String get copyLink => "Copy Link";

  @override
  String get shareToFeed => "Share To Feed";

  @override
  String get service => "Service";

  @override
  String get confirmPublic => " Are you sure you want to publish this voucher? Once published, buyers can use it, and you won't be able to edit it.";

  @override
  String get confirmUnpPublic =>  "Are you sure you want to unpublish this voucher Once unpublished, buyers cannot use it, and you will have the option to make edits.";

  @override
  String get confirmVoucher =>  "Are you want delete voucher?";

  @override
  String get deleteVoucher => "Delete Voucher";

  @override
  String get discountAmount => "Discount amount ";

  @override
  String get endDay => "End day";

  @override
  String get expireDate => "Expired";

  @override
  String get noExpiredDate => "No Expired Date";

  @override
  String get ongoing => "On going";

  @override
  String get startDay => "Start day";

  @override
  String get unpPublic => "Unpublic";

  @override
  String get upcoming => "Up coming";

  @override
  String get usedTotal => "Used/Total";

  @override
  String get viewDetail => "View detail";

  @override
  String nResult(int count) => plural(count,
      other: (count) => "$count results", one: "1 result", zero: "0 results");

  @override
  String get forr => "for";

  @override
  String get inn => "in";

  @override
  String get increasePrice => "Price:Low to high";

  @override
  String get decreasePrice => "Price:High to low";

  @override
  String get increaseRating => "Rating:Low to high";

  @override
  String get decreaseRating => "Rating:High to low";

  @override
  String get filterAz => "Name: A-Z";

  @override
  String get filterZa => "Name: Z-A";

  @override
  String get restaurantCategory => "Restaurant category";

  @override
  String get foodCategory => "Food category";
  
  @override
  String get allBuyers => "All buyers";
  
  @override
  String get noEndDate => "No end date";
  
  @override
  String get onlyViaShare => "Only via share";
  
  @override
  String get thisVoucherForAllProducts => 'This voucher is valid for all products and users throughout the promotional period.' ;
  
  @override
  String get thisVoucherForSomeProducts => 'This voucher is valid for some specific products throughout the promotional period.';

  @override
  String get copySuccessfully => "Copy Successfully";

  @override
  String get done => "Done";

  @override
  String noChange(String name) {
    return "Unable to change order status to $name";
  }

  @override
  String get followed => "Followed";

  @override
  String get history => "History";
  @override
  String get popularKeywords => "Popular keywords";

  @override
  String get voucherAlreadyExist => "Voucher name already exist or choose correct voucher type";

  @override
  String get allPaymentMethod => "All Payment Methods";

  @override
  String get dismiss => "Dismiss";

  @override
  String get requiredAddress => "This field is required";

  @override
  String get sendFrom => "Send from";

  @override
  String get variantSelection => "Variant selection";

  @override
  String availableProducts(num count) => plural(count,
      other: (count) => "$count available products", one: "1 available product", zero: "0 available products");

  @override
  String get requestOpenShop => "Request open shop";

  @override
  String get welcomeToSoctripSeller => "Welcome to Soctrip Seller";

  @override
  String get requestOpenShopPrompt => "To begin, initiate the registration process as a seller by providing the necessary information.";

  @override
  String get startRegistration => "Start registration";

  @override
  String get shopInformation => "Shop information";

  @override
  String get shopInfoPrompt => "Please enter the shop information. All fields are required.";

  @override
  String get merchantName => "Merchant name";

  @override
  String get enterMerchantName => "Enter merchant name";

  @override
  String get enterAddress => "Enter address";

  @override
  String get userInformation => "User information";

  @override
  String get userInfoPrompt => "Please enter the shop owner information. All fields are required";

  @override
  String get enterFullName => "Enter full name";

  @override
  String get email => "Email";

  @override
  String get enterEmail => "Enter email";

  @override
  String get phone => "Phone";

  @override
  String get enterPhone => "Enter phone number";

  @override
  String get idCard => "ID card";

  @override
  String get enterIdCard => "Enter ID card";

  @override
  String get haveAnOfflineStore => "Have an offline store";

  @override
  String get advanceInformation => "Advance information";

  @override
  String get advanceInfoPrompt =>"When you register for advanced information, you'll become a reputable seller with Soctrip.";

  @override
  String get openingTime => "Opening time";

  @override
  String get closedTime => "Closed time";

  @override
  String get time => "Time";

  @override
  String get workingDays => "Working days";

  @override
  String get selectDays => "Select days";

  @override
  String get enterAddressAdvance => "Enter address (e.g 123 street)";

  @override
  String get googleMapUrl => "Google map URL";

  @override
  String get enterGoogleMapUrl => "Enter google map URL";

  @override
  String get longitude => "Longitude";

  @override
  String get enterLongitude => "Enter longitude";

  @override
  String get latitude => "Latitude";

  @override
  String get enterLatitude => "Enter latitude";

  @override
  String get logoFile => "Logo file";

  @override
  String get uploadFile => "Upload file";

  @override
  String get enterAttachmentFile => "Enter attachment file";

  @override
  String get addAttachment => "Add attachment";

  @override
  String get sendRequest => "Send request";

  @override
  String get requestSentSuccessfully => "Request sent successfully!";

  @override
  String get sentRequestSuccessPrompt => "We are pleased to inform you that your request has been successfully submitted. We will review it and get back to you as soon as possible. Thank you for choosing us to address your needs.";

  @override
  String get pendingApproval => "Pending approval";

  @override
  String get backToHomepage => "Back to Homepage";

  @override
  String warningVoucher(price, currencyName) => "Please add an additional ${simpleCurrency(price, name: currencyName)} to use this voucher";

  @override
  String get inputNoteCheckOut => "Input a note for the seller...";

  @override
  String get freeShip => "Freeship";

  @override
  String socN(int count) {
    return "Soc ${compact(count)}";
  }

  @override
  String get dealOneUSD => "Deal \$1";

  @override
  String get hotVoucher => "Hot Voucher";

  @override
  String get trending => "Trending";

  @override
  String get travelItems => "Travel Items";

  @override
  String get newestArrival => "Newest arrival";

  @override
  String get errorNoShipmentMethodAvailable =>
      "Error: No available shipment methods from shop to you";

  @override
  String get addressLine1 => "Address line 1";

  @override
  String get addressLine2 => "Address line 2 (optional)";

  @override
  String get selectCountries => "Select countries";

  @override
  String get selectProvince => "Select province";

  @override
  String get selectDistrict => "Select district";

  @override
  String get stateProvince => "State/Province";

  @override
  String get electronicInvoices => "Electronic invoices";

  @override
  String get desElectronicInvoices => "Soctrip only issues electronic invoices";

  @override
  String get companyName => "Company Name";

  @override
  String get companyAddress => "Company Address";

  @override
  String get taxCode => "Tax Code";

  @override
  String get enterCompanyName => "Enter Company Name";

  @override
  String get enterCompanyAddress => "Enter Company Address";

  @override
  String get enterTaxCode => "Enter Tax Code";

  @override
  String get firstName => "First Name";

  @override
  String get lastName => "Last Name";

  @override
  String get addressLineOne => "Address Line 1";

  @override
  String get addressLineTwo => "Address Line 2";

  @override
  String get zipCode => "Zipcode";

  @override
  String get billingAddress => "Billing Address";

  @override
  String get enterFirstName => "Enter First Name";

  @override
  String get enterLastName => "Enter Last Name";

  @override
  String get enterZipcode => "Enter zipcode";

  @override
  String get used => "Used";

  @override
  String get noShopVoucher => "No shop vouchers yet";

  @override
  String get noShippingVoucher => "No shipping vouchers yet";

  @override
  String get descriptionNoVoucher => "Please input any valid voucher codes into the provided input bar above";

  @override
  String get shipment => "Shipment";

  @override
  String get pleaseSelectShipment => "Please select shipment";

  @override
  String get categories => "Categories";

  @override
  String get selectCategory => "Select category";

  @override
  String get detailedInformation => "Detailed information";

  @override
  String get voucherDisplayApplicabeProduct => "Voucher display & Applicable product";

  @override
  String get applyForArea => "Area";

  @override
  String get selectArea => "Choose area";

  @override
  String get missBasicInformation => "Please check again information of Basic Information";

  @override
  String get missCategory => "Please add category of this voucher";

  @override
  String get missDetailInformation => "Please check again information of Detailt Information";

  @override
  String get missProduct => "Please add products of this voucher";

  @override
  String get missValidPeriod => "Please check again information of Valid period";

  @override
  String get missVoucherSetting => "Please check again information of Voucher Setting";
  @override
  String get dob_1 => "Jan";
  @override
  String get dob_2 => "Feb";
  @override
  String get dob_3 => "Mar";
  @override
  String get dob_4 => "Apr";
  @override
  String get dob_5 => "May";
  @override
  String get dob_6 => "Jun";
  @override
  String get dob_7 => "July";
  @override
  String get dob_8 => "Aug";
  @override
  String get dob_9 => "Sep";
  @override
  String get dob_10 => "Oct";
  @override
  String get dob_11 => "Nov";
  @override
  String get dob_12 => "Dec";
   @override
  String get selectStartDate => "Select start date";
  @override
  String get selectEndDate => "Select end date";

  @override
  String get enableExportElectronicInvoices => "Enable buyers to export electronic invoices";

  @override
  String get waitingApproveUpdateShop => "Your request is waiting for approval";

  @override
  String get waitingApproveUpdateShopPrompt => "You shop is currently under review by our team.We're working to ensure it meets our standards.We'll notify you once it's approved and ready for business. Thank you for your patience.";

  @override
  String get updateShop => "Update shop";

  @override
  String get megaMenu => "Mega Menu";

  @override
  String get center => "Center";

  @override
  String get social => "Social";

  @override
  String get shop => "Shop";

  @override
  String get restaurant => "Restaurant";

  @override
  String get travelTour => "Travel Tour";

  @override
  String get notDeleteAddressDefault => "You cannot delete default address";

  @override
  String get deliveryDiscount => "Delivery discount";

  @override
  String get requestOpenRestaurant => "Request open restaurant";

  @override
  String get restaurantInfo => "Restaurant information";

  @override
  String get restaurantInfoPrompt => "Please enter the restaurant information. All fields are required";

  @override
  String get requestToOpenRestaurant => "Request to open restaurant";

  @override
  String get updateRestaurant => "Update restaurant";

  @override
  String get emptyCart => "Your cart is empty";

  @override
  String get chooseShipment => "Choose the shipment";

  @override
  String get descriptionEmptyCart => "Your cart is waiting for you. Add some items to \ncomplete your purchase.";

  @override
  String get unlimited => "Unlimited";

  @override
  String get terrible => "Terrible";

  @override
  String get poor => "Poor";

  @override
  String get fair => "Fair";

  @override
  String get amazing => "Amazing";
}



