/*
* Author: Diep Vo
*
* Please be aware that this file was generated by 'flutter gen-l10n'.
* However, note that 'flutter gen-l10n' is not compatible with
* Flutter packages and only works with Flutter applications.
* Hence, I manually copied this code to the source folder.
* We plan to gradually add translatable strings to this file over time.
* The translation string interface
* should be defined in ecommerce_translatable.dart
* */

import 'shared_localizations.dart';

/// The translations for Vietnamese (`vi`).
class SharedLocalizationsVi extends SharedLocalizations {
  SharedLocalizationsVi([String locale = 'vi']) : super(locale);

  @override
  String get welcomeToEcommerce => "Chào mừng đến với eCommerce";

  @override
  String helloUser(String userName) {
    return "Chào $userName";
  }

  @override
  String userHaveNApple(String userName, int appleCount) {
    return plural(appleCount,
        zero: "$userName không có trái náo nào cả",
        other: (count) => "$userName có $count trái táo");
  }

  @override
  String heOrSheDidIt(String sex) {
    return select(sex, {
      "male": "Anh ấy đã làm được",
      "female": "Chị ấy đã làm được",
      "other": "Họ đã làm được",
    });
  }


  @override
  String get searchForProvince => "Tìm tỉnh thành";


  @override
  String get noResultsFound => "Không có kết quả";

  @override
  String get someFamousLocations => "Vài địa điểm nổi tiếng";

  @override
  String get locationsNearYou => "Xung quanh bạn";

  @override
  String characters(int current, int limit) {
    return "$current/$limit ký tự";
  }

  @override
  String get dataNotFound => "Không có dữ liệu";

  @override
  String get error => "Lỗi";

  @override
  String get ok => "OK";

  @override
  String nProduct(int count) => "${compact(count)} Sản phẩm";

  @override
  String get customerReviews => "Đánh giá từ khách hàng";

  @override
  String nReview(num count) => "${compact(count)} Đánh giá";

  @override
  String get size => "Kích cỡ";

  @override
  String get color => "Màu sắc";

  @override
  String get helpful => "Hữu ích";

  @override
  String get report => "Báo cáo";

  @override
  String get claim => "Nhận";

  @override
  String get voucher => "Phiếu giảm giá";

  @override
  String pagination(String currentPage, String limitPage) {
    return "Trang $currentPage/$limitPage";
  }

  @override
  String get allProduct => "Tất cả sản phẩm";

  @override
  String voucherDiscount(String name) {
    return "Voucher discount $name";
  }

  @override
  String minSentVoucher(String value) {
    return "Đơn hàng tối thiểu $value";
  }

  @override
  String validVoucher(String ranger) {
    return "Hiệu lực đến $ranger";
  }

  @override
  String get follow => "Theo dõi";

  @override
  String get chat => "Nhắn tin";

  @override
  String get viewAll => "Xem tất cả";

  @override
  String get popularItemInThisSeason => "Mặt hàng phổ biến trong mùa này";

  @override
  String get dealUnder => "Mặt hàng giảm giá";

  @override
  String get purchaseHistory => "Đơn hàng của tôi";

  @override
  String get apply => "Áp dụng";

  @override
  String get brand => "Thương hiệu";

  @override
  String get condition => "Tình trạng";

  @override
  String get filter => "Lọc";

  @override
  String get goToCart => "Đến giỏ hàng";

  @override
  String get productCategory => "Danh mục sản phẩm";

  @override
  String get rating => "Đánh giá";

  @override
  String get region => "Khu vực";

  @override
  String get reset => "Huỷ";

  @override
  String get searchSuggestion => "Đề xuất tìm kiếm:";

  @override
  String get shipmentMethod => "Phương thức giao hàng";

  @override
  String get sort => "Sắp xếp";

  @override
  String get priceRange => "Khoảng giá";

  @override
  String get seeLess => "Thu hẹp";

  @override
  String get seeMore => "Mở rộng";

  @override
  String get all => "Tất cả";

  @override
  String get cosmetic => "Thời Trang";

  @override
  String get fashion => "Mỹ Phẩm";

  @override
  String searchResult(int start, int end, int total, String category) {
    return "${compact(start)} - ${compact(end)} trong ${compact(total)} kết quả thuộc $category";
  }

  @override
  String searchResults(int total, String? category, String? label) {
    String res = "${compact(total)} kết quả ";
    if (category != null) {
      res = "$res với $category ";
    }
    if (label != null) {
      res = "$res thuộc $label ";
    }
    return res;
  }

  @override
  String get menu => "Tuỳ Chọn";

  @override
  String get cart => "Giỏ Hàng";

  @override
  String get item => "Món";

  @override
  String get myCart => "Giỏ Hàng của Tôi";

  @override
  String get myOrder => "Đơn Hàng của Tôi";

  @override
  String get home => "Nhà riêng";

  @override
  String get addressDefault => "Mặc định";

  @override
  String get office => "Văn Phòng";

  @override
  String get addNewAddress => "Thêm mới địa chỉ";

  @override
  String get cancel => "Cancel";

  @override
  String get address => "Địa chỉ";

  @override
  String get addressType => "Loại địa chỉ";

  @override
  String get city => "Thành Phố";

  @override
  String get deleteAddress => "Xóa địa chỉ";

  @override
  String get district => "Quận/huyện";

  @override
  String get fullName => "Họ và tên";

  @override
  String get phoneNumber => "Số điện thoại";

  @override
  String get setAsDefaultAddress => "Địa chỉ mặc định";

  @override
  String get ward => "Phường/xã";

  @override
  String get streetName => "Tên đường";

  @override
  String get checkout => "Thanh toán";

  @override
  String get total => "Tổng";

  @override
  String variation(String value) {
    return "Phân loại: $value";
  }

  @override
  String get shopVouchers => "Shop vouchers";

  @override
  String get vouchers => "Vouchers";

  @override
  String get selectVouchers => "Chọn vouchers";

  @override
  String get paymentMethod => "Phương thức thanh toán";

  @override
  String get cod => "Thanh toán khi nhận hàng";

  @override
  String get onlineBanking => "Online banking & Direct debit";

  @override
  String get paypal => "Paypal";

  @override
  String get creditCard => "Thẻ tín dụng";

  @override
  String get paymentDetails => "Chi tiết thanh toán";

  @override
  String get subtotal => "Tổng tiền hàng";

  @override
  String get allProducts => "Tất cả sản phẩm";

  @override
  String get visitShop => "Vào cửa hàng";

  @override
  String get discounts => "Giảm giá";

  @override
  String get deliveryFee => "Phí vận chuyển";

  @override
  String get buyNow => "Mua ngay";

  @override
  String cartShowNumberItems(int number) {
    return "Giỏ hàng: ${compact(number)} món.";
  }

  @override
  String get changeEmailAddress => "Đổi địa chỉ email";

  @override
  String get description => "Mô Tả";

  @override
  String get flashSale => "Ưu đãi chớp nhoáng";

  @override
  String get freeReturnWithin7Days => "Miễn phí trả hàng trong vòng 7 ngày";

  @override
  String get freeShipping => "Miễn phí vận chuyển";

  @override
  String freeShippingOnOrderFrom(cost, currencyName) =>
      "Miễn phí vận chuyển cho đơn từ  ${simpleCurrency(cost, name: currencyName)}";

  @override
  String get productInformation => "Thông Tin Sản Phẩm";

  @override
  String get quantity => "Số lượng";

  @override
  String get returnGoods => "Trả hàng";

  @override
  String get stock => "Còn lại:";

  @override
  String get customerReview => "Đánh giá khách hàng";

  @override
  String get follower => "Người theo dõi";

  @override
  String get product => "Sản phẩm";

  @override
  String get reviews => "Đánh giá";

  @override
  String get Select => "Chọn";

  @override
  String get addressList => "Sổ Địa Chỉ";

  @override
  String get cancelled => "Đã huỷ";

  @override
  String get car => "Xe";

  @override
  String get checkOut => "Xác nhận đơn hàng";

  @override
  String get flightTicket => "Vé Máy Bay";

  @override
  String get food => "Ẩm Thực";

  @override
  String get helpCenter => "Trung Tâm Trợ Giúp";

  @override
  String get homePage => "Trang Chủ";

  @override
  String get hotel => "Khách Sạn";

  @override
  String get logOut => "Đăng Xuất";

  @override
  String get manage => "Quản Lý";

  @override
  String get myShop => "Cửa Hàng Của Tôi";

  @override
  String get productDetails => "Chi Tiết Sản Phẩm";

  @override
  String get purchasing => "Mua Bán";

  @override
  String get securityCenter => "Trung Tâm Bảo Mật";

  @override
  String get settings => "Cài Đặt";

  @override
  String get tour => "Chuyến Đi";

  @override
  String get addToCart => "Thêm vào giỏ hàng";

  @override
  String nItem(int count) => "${compact(count)} sản phẩm";

  @override
  String priceCheckOut(cost, currencyName) =>
      simpleCurrency(cost, name: currencyName);

  @override
  String get datanotfound => "Không tìm thấy dữ liệu. Vui lòng quay lại sau.";

  @override
  String get categoryList => "Danh mục sản phẩm";

  @override
  String get confirm => "Xác nhận";

  @override
  String get viewMore => "Xem thêm";

  @override
  String get shippingVouchers => "Mã giảm giá vận chuyển";

  @override
  String discountVoucher(String value) {
    return "Discount $value%";
  }

  @override
  String expiredDayVoucher(String ranger) {
    return "Hiệu lực đến $ranger";
  }

  @override
  String minSpendVoucher(cost, currencyName) =>
      "Đơn hàng tối thiểu ${simpleCurrency(cost, name: currencyName)}";

  @override
  String freeShipVoucher(cost, currencyName) =>
      "Miễn phí vận chuyển ${simpleCurrency(cost, name: currencyName)}";

  @override
  String get statusCancel => "Đã hủy";

  @override
  String get statusPaymentFailed => "Thanh toán thất bại";

  @override
  String get statusPaymentSuccessfully => "Thanh toán thành công";

  @override
  String get statusDelivering => "Đang giao hàng";

  @override
  String get statusDelivered => "Đã giao hàng";

  @override
  String get statusCompleted => "Hoàn thành";

  @override
  String get statusRefund => "Trả hàng";

  @override
  String get orderTotal => "Tổng đơn hàng";

  @override
  String get reOrder => "Mua lại";

  @override
  String get rePay => "Thanh toán lại";

  @override
  String get cancelOrder => "Hủy đơn hàng";

  @override
  String get refundOrder => "Trả hàng";

  @override
  String get receivedOrder => "Đã nhận hàng";

  @override
  String get toPay => "Chờ thanh toán";

  @override
  String get toShip => "Vận chuyển";

  @override
  String get toDelivery => "Chờ lấy hàng";

  @override
  String get deliveredMyOrder => "Đang giao";

  @override
  String get completedMyOrder => "Đã giao";

  @override
  String get cancelMyOrder => "Đã hủy";

  @override
  String get refundMyOrder => "Trả hàng";

  @override
  String get noData => "Dữ liệu trống";

  @override
  String addToCartSuccessfully(String productName) {
    return "Đã thêm $productName vào giỏ hàng.";
  }

  @override
  String get noItem => "Chưa có dữ liệu";

  @override
  String get more => "Xem thêm";

  @override
  String get orderManagement => "Quản Lý Đơn Hàng";

  @override
  String get productCategories => "Danh Mục Sản Phẩm";

  @override
  String get sellerChannel => "Kênh người bán";

  @override
  String get shopAnalytics => "Phân Tích Cửa Hàng";

  @override
  String get modifyCategoryHint =>
      'Chọn loại danh mục phù hợp sẽ giúp đảm bảo sản phẩm của bạn được thể hiện đúng vị trí mà người dùng tìm kiếm các kết quả liên quan, giúp bạn tiếp cận khách hàng mục tiêu của mình hiệu quả hơn.';

  @override
  String get addCategory => "Thêm danh mục mới";

  @override
  String get addProduct => "Thêm sản phẩm mới";

  @override
  String get addSubCategory => "Thêm danh mục phụ mới";

  @override
  String get categoryDeleted => "Danh mục đã được xoá.";

  @override
  String get categoryPublished => "Danh mục đã được mở.";

  @override
  String get categoryUpdated => "Danh mục đã được cập nhật.";

  @override
  String get delete => "Xoá";

  @override
  String get edit => "Sửa";

  @override
  String get editCategory => "Chỉnh sửa danh mục";

  @override
  String get noCategoryFound => "Không tìm thấy danh mục nào";

  @override
  String get noCategoryFoundHint =>
      'Danh mục sản phẩm bạn tạo ra sẽ được hiển thị tại đây. Bạn có thể nhấn nút bên dưới để bắt đầu tạo danh mục mới.';

  @override
  String get save => "Lưu";

  @override
  String get selectCategoryType => "Chọn loại danh mục";

  @override
  String get categoryAdded => "Danh mục đã được thêm vào.";

  @override
  String get categoryName => "Tên danh mục";

  @override
  String get categoryType => "Loại danh mục";

  @override
  String get enterCategoryName => "Nhập tên danh mục";

  @override
  String get selectType => "Chọn loại danh mục";

  @override
  String get choose => "Chọn";

  @override
  String get deleteCategory => "Xoá danh mục";

  @override
  String get deleteCategoryHint =>
      "Nếu bạn xóa một danh mục, tất cả các danh mục phụ bên trong nó cũng sẽ bị xóa. Bạn có chắc chắn muốn xóa danh mục này không?";

  @override
  String get addCategories => "Tạo danh mục mới";

  @override
  String get addSubCategories => "Tạo danh mục phụ mới";

  @override
  String get editCategories => "Chỉnh sửa danh mục";

  @override
  String get goodQuality => "Chất lượng tốt";

  @override
  String get withinMedias => "Chuẩn";

  @override
  String get withinComments => "Sản phẩm đẹp";

  @override
  String get fastDelivery => "Giao hàng nhanh";

  @override
  String get carefulPacking => "Đóng gói cẩn thận";

  @override
  String get reasonablePrices => "Giá cả hợp lý";

  @override
  String get goodAttitude => "Thái độ tốt";

  @override
  String get loading => "Đang tải...";

  @override
  String get confirmDeleteAddress => "Bạn có chắc muốn xóa địa chỉ ?";

  @override
  String get create => "Tạo mới";

  @override
  String get editAddress => "Chỉnh sửa địa chỉ";

  @override
  String get rateTheProducts => "Đánh giá sản phẩm";

  @override
  String get photoVideo => "Ảnh/thước phim";

  @override
  String get giveUsYourFeedback =>
      "Hãy cho chúng tôi thông tin phản hồi của bạn";

  @override
  String get textPlaceHolderFeedback => "Bạn nghĩ như thế nào về sản phẩm này?";

  @override
  String get questionFeedback =>
      "Bạn thích gì nhất? Hãy chia sẻ nó với Soctrip ngay nhé.";

  @override
  String get questionRateStar =>
      "Trải nghiệm của bạn với sản phẩm này như thế nào?";

  @override
  String get submit => "Gửi";

  @override
  String get variationProduct => "Phân loại";

  @override
  String checkoutGetItem(int total) {
    return "Mua hàng($total)";
  }

  @override
  String get no => "Không";

  @override
  String get yes => "Đồng ý";

  @override
  String get titleDeleteItem => "Xóa sản phẩm";

  @override
  String get descriptionDeleteItem => "Bạn có chắc chắn muốn xóa sản phẩm này?";

  @override
  String get changeDefaultAddress => "Đổi địa chỉ mặc định";

  @override
  String get confirmDefaultAddress => "Bạn có chắc muốn đổi địa chỉ mặc định ?";

  @override
  String get country => "Quốc gia";

  @override
  String get search => "Tìm kiếm";

  @override
  String get searchInShop => "Tìm kiếm trong cửa hàng";

  @override
  String get noProductFound => "Chưa có sản phẩm nào.";

  @override
  String get inStockWithColon => "Trong kho: ";

  @override
  String get priceWithColon => "Giá: ";

  @override
  String get categoryEdited => "Danh mục đã điều chỉnh.";

  @override
  String get categoryUnpublished => "Danh mục đã tắt.";

  @override
  String get errorDelete => "Vui lòng xoá danh mục con trước.";

  @override
  String get plsSelectOptionToBuy => "Vui lòng chọn các lựa chọn để mua.";

  @override
  String get addNewProduct => "Add new product";

  @override
  String get addOption => "Add option";

  @override
  String get addVariant => "Add variant";

  @override
  String get attribute => "Attribute";

  @override
  String get category => "Category";

  @override
  String get generalInformation => "General information";

  @override
  String get inStock => "In stock";

  @override
  String get newAttribute => "New attribute";

  @override
  String get options => "Options";

  @override
  String get price => "Price";

  @override
  String get pricing => "Pricing";

  @override
  String get productDescription => "Product description";

  @override
  String get productDetail => "Product detail";

  @override
  String get productName => "Product Name";

  @override
  String get publish => "Công khai voucher";

  @override
  String get recommendedForImage =>
      "Recommended image ratios for uploads are 3:4 or 1:1.";

  @override
  String get salePrice => "Sale Price";

  @override
  String get selectImage => "Select Image";

  @override
  String get settingVariantPrices => "Setting variant prices";

  @override
  String get settingVariation => "Setting variation";

  @override
  String get tags => "Tags";

  @override
  String get totalUploadedImages => "Total uploaded images:";

  @override
  String get value => "Value";

  @override
  String get variantName => "Variant name";

  @override
  String get variants => "Variants";

  @override
  String get warningChooseProduct => "Vui lòng chọn sản phẩm";

  @override
  String get checkoutSuccess => "Cảm ơn bạn đã đặt hàng";

  @override
  String get checkoutFail => "Thanh toán thất bại";

  @override
  String get orderID => "Mã đơn hàng";

  @override
  String get transactionDate => "Ngày giao dịch";

  @override
  String get trackOrder => "Theo dõi đơn hàng";

  @override
  String get continueShopping => "Tiếp tục mua sắm";

  @override
  String get dateFormatForCalendar => "dd/MM/yyyy";

  @override
  String get setAsDraft => "Set as Draft";

  @override
  String get addNewAttribute => "Tạo thuộc tính ";

  @override
  String get updateAttribute => "Chỉnh sửa thuộc tính";

  @override
  String get selects => "selects";

  @override
  String get applyForAll => "Apply for all variants";

  @override
  String get nothingIsSelected => "Nothing is selected";

  @override
  String get active => "Active";

  @override
  String get draft => "Draft";

  @override
  String get outOfStock => "Out Of Stock";

  @override
  String get max => "Tối đa";

  @override
  String get min => "Tối thiểu";

  @override
  String get confirmDeleteProduct => "Bạn có muốn xóa sản phẩm";

  @override
  String get deleteProduct => "Xóa sản phẩm";

  @override
  String get confirmSetAsProduct => "Do you want to set as draft the product";

  @override
  String get valueException => "Giá trị ngoại lệ";
  @override
  String get titleThanksRate => "Cảm ơn xếp hạng của bạn!";

  @override
  String get contentThanksRate => "Cảm ơn bạn đã đánh giá sản phẩm.";

  @override
  String get close => "Đóng";

  @override
  String get good => "Tốt";

  @override
  String get nothingImageSelect => "Không có gì được chọn";

  @override
  String get notData => "Không có dữ liệu!";

  @override
  String get orderDetail => "Chi tiết đơn hàng";

  @override
  String get orderInfo => "Thông tin đơn hàng";

  @override
  String get orderId => "Mã đơn hàng";

  @override
  String get status => "Trạng thái";

  @override
  String get orderDate => "Ngày đặt hàng";

  @override
  String get note => "Ghi chú";

  @override
  String get name => "Tên";

  @override
  String get deliveryInfo => "Thông tin vận chuyển";

  @override
  String get orderStatus => "Trạng thái đơn hàng";

  @override
  String get orderStatusNote => "Ghi chú trạng thái đơn hàng";

  @override
  String get orderStatusDetail => "Chi tiết trạng thái đơn hàng";

  @override
  String get productList => "Danh sách sản phẩm";

  @override
  String get paymentInformation => "Thông tin thanh toán";

  @override
  String get subStatus => "Trạng thái phụ";

  @override
  String get messageForCustomer => "Nhận xét từ khách hàng";

  @override
  String get textPlaceHolderOrderManagement => "Viết đánh giá";

  @override
  String get descriptionMessage =>
      "Người dùng sẽ nhận được tin nhắn này (bao gồm URL chi tiết đơn hàng) thông qua hộp trò chuyện Soctrip. ";

  @override
  String get clickToUpload => "Đẩy tệp";

  @override
  String get descriptionUpload => "SVG, PNG, JPG or GIF (max. 800x400px)";

  @override
  String get attachments => "Tệp";

  @override
  String get cancelReason => "Lý do hủy";

  @override
  String get chooseReason => "Chọn lý do hủy";

  @override
  String get chooseSubStatus => "Chọn trạng thái phụ";

  @override
  String get inputNote => "Nhập chú thích";

  @override
  String get pleaseChooseStatusFirst => "Vui lòng chọn trạng thái đầu tiên";

  @override
  String get descriptionAttachmentOne =>
      "Gửi cập nhật cho người dùng \nNgười dùng sẽ nhận được thông báo về trạng thái đơn hàng này trên Soctrip và email của họ.";

  @override
  String get descriptionAttachmentTwo =>
      "Hiển thị bước này cho người dùng \nNgười dùng có thể xem bước này trong “Chi tiết đơn hàng”.";

  @override
  String get updateStatus => "Cập nhật trạng thái";

  @override
  String get descriptionCancelOrder =>
      "Vui lòng chọn lý do hủy. Hãy lưu ý rằng điều này sẽ hủy tất cả các mặt hàng trong đơn đặt hàng và hành động không thể hoàn tác";

  @override
  String get reviewRating => "Xem đánh giá";

  @override
  String get datetimeFormatForCalendar => "dd/MM/yyyy • HH:mm";

  @override
  String get favorite => "Yêu thích";

  @override
  String get shopping => "Mua sắm";

  @override
  String get yourMarket => "Quanh bạn";

  @override
  String get closing => "Đóng của";

  @override
  String get opening => "Mở cửa";

  @override
  String get viewLess => "Thu nhỏ";

  @override
  String get searchProduct => "Tìm sản phẩm";

  @override
  String get selectAll => "Chọn tất cả";

  @override
  String get applicableProduct => "Applicable product";

  @override
  String get basicInformation => "Basic information";

  @override
  String get discountType => "Discount type";

  @override
  String get maxDistributionPerBuyer => "Max distribution per buyer";

  @override
  String get maximumDiscountPrice => "Maximum discount price";

  @override
  String get minimumOrderPrice => "Minimum order price";

  @override
  String get platform => "Platform";

  @override
  String get special => "Special";

  @override
  String get validPeriod => "Valid period";

  @override
  String get voucherCode => "Voucher code";

  @override
  String get voucherDisplaySettings => "Voucher display settings";

  @override
  String get voucherName => "Voucher name";

  @override
  String get voucherSettings => "Voucher settings";

  @override
  String get voucherType => "Voucher type";

  @override
  String get voucherDetail => "Voucher detail";

  @override
  String get plsGoToWeb => "Vui lòng truy cập web để sử dụng tính năng này";

  @override
  String get shopBuilder => "Thiết kế Shop";

  @override
  String get voucherManagement => "Quản lý mã giảm giá";

  @override
  String get addNewVoucher => "Thêm mã giảm giá mới";

  @override
  String get createPost => "Tạo bài viết";

  @override
  String hintCreatePost(String content) {
    return "Chào $content, Chia sẻ cảm xúc của bạn!";
  }

  @override
  String get post => "Đăng";

  @override
  String get private => "Riêng tư";

  @override
  String get public => "Công khai";

  @override
  String get shareToFeedSuccess => "Chia sẽ thành công";

  @override
  String get myRestaurant => "Nhà hàng của tôi";

  @override
  String get copyLink => "Sao chép";

  @override
  String get shareToFeed => "Chia sẽ";

  @override
  String get service => "Dịch vụ";

  @override
  String get confirmPublic => " Are you sure you want to publish this voucher? Once published, buyers can use it, and you won't be able to edit it.";

  @override
  String get confirmUnpPublic =>  "Are you sure you want to unpublish this voucher Once unpublished, buyers cannot use it, and you will have the option to make edits.";

  @override
  String get confirmVoucher =>  "Bạn có muốn xóa mã giảm giá?";

  @override
  String get deleteVoucher => " Xóa mã giảm giá";

  @override
  String get discountAmount => "Discount amount ";

  @override
  String get endDay => "Ngày kết thúc";

  @override
  String get expireDate => "Expired";

  @override
  String get noExpiredDate => "No Expired Date";

  @override
  String get ongoing => "On going";

  @override
  String get startDay => "Ngày bắt đầu";

  @override
  String get unpPublic => "Unpublic";

  @override
  String get upcoming => "Up coming";

  @override
  String get usedTotal => "Sử dụng/ Tổng";

  @override
  String get viewDetail => "Xem chi tiết";

  @override
  String nResult(int count) => plural(count,
      other: (count) => "$count kết quả", one: "1 kết quả", zero: "0 kết quả");

  @override
  String get forr => "cho";

  @override
  String get inn => "trong";

  @override
  String get increasePrice => "Giá: Thấp lên cao";

  @override
  String get newestArrival => "Sản Phẩm mới";

  @override
  String get decreasePrice => "Giá: Cao xuống thấp";

  @override
  String get increaseRating => "Đánh giá: Cao xuống thấp";

  @override
  String get decreaseRating => "Đánh giá: Thấp lên cao";

  @override
  String get filterAz => "Tên: A-Z";

  @override
  String get filterZa => "Tên: Z-A";

  @override
  String get restaurantCategory => "Danh mục nhà hàng";

  @override
  String get foodCategory => "Danh mục món ăn";

  @override
  String get plsInputAlphabet =>
      "Vui lòng chỉ nhập các ký tự chữ cái (A-Z) và số (0-9), với độ dài tối đa 5 ký tự.";

  @override
  String get kindlyFurnishVoucherDetails => 'Kindly furnish essential voucher details. All fields are mandatory.';

  @override
  String get plsConfigVoucherReward => "Please configure all voucher reward parameters. This is the key feature of the voucher";

  @override
  String get byPercentage => "Theo phần trăm";

  @override
  String get chooseYourPaymentMethod => "Chọn phương thức thanh toán";

  @override
  String get chooseYourPlatform => "Chọn nơi áp dụng";

  @override
  String get chooseYourVoucherType => "Chọn loại mã giảm giá";

  @override
  String get enhanceYourCustomerUnderstanding => "Giúp khách hàng hiểu được mã giảm giá của bạn.";

  @override
  String get fixAmount => "Số tiền cố định";

  @override
  String get inputDescriptionHere => "Nhập mô tả ở đây";

  @override
  String get inputHere => "Nhập ở đây";

  @override
  String get inputVoucherName => "Nhập tên mã giảm giá";

  @override
  String get inputYourVoucherCode => "Nhập mã";

  @override
  String get noExpiryDate => "Không hết hạn";

  @override
  String get preview => "Xem trước";

  @override
  String get automaticallyDisplayOnHomePage => "Voucher sẽ được tự động hiển thị trên trang chủ cửa hàng, trang sản phẩm, trang giỏ hàng và cũng có thể chia sẻ trên Soctrip Merchant Live.";

  @override
  String get displayOnAllPages => "Thể hiện ở tất cả các trang mã giảm giá";

  @override
  String get informCustomerDemographic => "Vui lòng xác định đối tượng khách hàng mà bạn dự định nhắm đến khi phát hành mã giảm giá";

  @override
  String get specificProducts => "Sản phẩm cụ thể";

  @override
  String get toBeSharedThroughVoucherCode => "Có thể chia sẻ được qua mã giảm gía";

  @override
  String get onlySharableViaVoucherCode => "Mã giảm giá được chia sẽ sẽ được lưu lại trong ví cá nhân";

  @override
  String get selectVoucherType => "Chọn loại mã giảm giá";

  @override
  String get exclusivelyVisibleDuringLiveStream => 'Mã giảm giá này chỉ hiển thị độc quyền khi xem buổi phát trực tiếp và chỉ những người xem buổi phát trực tiếp mới có quyền truy cập vào nó.';

  @override
  String get onlyDisplayOnLiveStream => 'Chỉ xuất hiện trong livestream';

  @override
  String get voucherPreview => "Mã giảm giá";

  @override
  String get reward => "Phần thưởng";

  @override
  String get targetBuyer => "Mục tiêu người mua";

  @override
  String get limitedRedemption => "Mã giảm giá giới hạn";

  @override
  String getAVoucher(cost, currencyName){
    return "Giảm ${currencyName == "%" ? "$cost%" : simpleCurrency(cost, name: currencyName)}";
  }

  @override
  String minimumOrderPrices(cost, currencyName){
    return "Đơn hàng tối thiểu: ${currencyName == "%" ? "$cost%" : simpleCurrency(cost, name: currencyName)}";
  }

  @override
  String get addVoucher => "Thêm mã giảm giá";

  @override
  String get setAmount => "Định giá tiền";

  @override
  String get noLimit => "Không giới hạn";

  @override
  String get allPlatforms => "Tất cả nền tảng";

  @override
  String get app => "Ứng dụng di động";

  @override
  String get web => "Trên website";

  @override
  String get required => "yêu cầu nhập";

  @override
  String get selectPlatform => "Chọn nơi áp dụng";

  @override
  String get plsInputAllOptions => "Vui lòng nhập hết các trường yêu cầu để tạo mã giảm giá";

  @override
  String get allBuyers => "Tất cả người mua";

  @override
  String get noEndDate => "Không hết hạn";

  @override
  String get onlyViaShare => "Chỉ qua chia sẻ";

  @override
  String get thisVoucherForAllProducts => 'Mã giảm giá này có giá trị cho tất cả sản phẩm trong suốt thời gian khuyến mãi.' ;

  @override
  String get thisVoucherForSomeProducts => 'Mã giảm giá này có giá trị cho 1 số sản phẩm sản phẩm trong suốt thời gian khuyến mãi.';

  @override
  String get copySuccessfully => "Sao chép thành công";

  @override
  String get done => "Xong";

  @override
  String noChange(String name) {
    return "Không thể thay đổi trạng thái đơn hàng thành $name";
  }

  @override
  String get followed => "Đã theo dõi";

  @override
  String get history => "Lịch sử";

  @override
  String get popularKeywords => "Từ khóa phổ biến";

  @override
  String get voucherAlreadyExist => "Tên mã giảm giá đã tồn tại hoặc chưa chọn loại voucher";

  @override
  String get allPaymentMethod => "Tất cả phương thức thanh toán";

  @override
  String get dismiss => "Đóng";

  @override
  String get requiredAddress => "Trường này không được để trống";

  @override
  String get sendFrom => "Gửi từ";

  @override
  String get variantSelection => "Chọn loại";

  @override
  String availableProducts(num count) => plural(count,
      other: (count) => "$count sản phẩm có sẵn", one: "1 sản phẩm có sẵn", zero: "0 sản phẩm có sẵn");

  @override
  String get requestOpenShop => "Yêu câu mở cửa hàng";

  @override
  String get welcomeToSoctripSeller => "Chào mừng bạn đến với Soctrip Seller";

  @override
  String get requestOpenShopPrompt => "Để bắt đầu, bắt đầu quá trình đăng ký như một người bán bằng cách cung cấp thông tin cần thiết.";

  @override
  String get startRegistration => "Bắt đầu đăng ký";

  @override
  String get shopInformation => "Thông tin cửa hàng";

  @override
  String get shopInfoPrompt => "Xin vui lòng nhập thông tin cửa hàng. Tất cả các trường đều bắt buộc.";

  @override
  String get merchantName => "Tên nhà cung cấp";

  @override
  String get enterMerchantName => "Nhập tên nhà cung cấp";

  @override
  String get enterAddress => "Nhập địa chỉ";

  @override
  String get userInformation => "Thông tin người dùng";

  @override
  String get userInfoPrompt => "Xin vui lòng nhập thông tin chủ cửa hàng. Tất cả các trường là bắt buộc.";

  @override
  String get enterFullName => "Nhập họ và tên";

  @override
  String get email => "Email";

  @override
  String get enterEmail => "Nhập email";

  @override
  String get phone => "Điện thoại";

  @override
  String get enterPhone => "Nhập số điện thoại";

  @override
  String get idCard => "Thẻ căn cước công dân";

  @override
  String get enterIdCard => "Nhập căn cước công dân";

  @override
  String get haveAnOfflineStore => "Có cửa hàng cố định";

  @override
  String get advanceInformation => "Thông tin nâng cao.";

  @override
  String get advanceInfoPrompt => "Khi bạn đăng ký thông tin nâng cao, bạn sẽ trở thành một người bán đáng tin cậy trên Soctrip.";

  @override
  String get openingTime => "Thời gian mở cửa";

  @override
  String get closedTime => "Thời gian đóng cửa";

  @override
  String get time => "Thời gian";

  @override
  String get workingDays => "Các ngày làm việc";

  @override
  String get selectDays => "Chọn ngày.";

  @override
  String get enterAddressAdvance => "Nhập địa chỉ (ví dụ: đường 123).";

  @override
  String get googleMapUrl => "Đường dẫn Google map";

  @override
  String get enterGoogleMapUrl => "Nhập đường dẫn google map";

  @override
  String get longitude => "Kinh độ";

  @override
  String get enterLongitude => "Nhập kinh độ";

  @override
  String get latitude => "Vĩ độ";

  @override
  String get enterLatitude => "Nhập vĩ độ";

  @override
  String get logoFile => "Tệp biểu tượng";

  @override
  String get uploadFile => "Tải lên tập tin";

  @override
  String get enterAttachmentFile => "Nhập tập tin đính kèm";

  @override
  String get addAttachment => "Thêm tập tin";

  @override
  String get sendRequest => "Gửi yêu cầu";

  @override
  String get requestSentSuccessfully => "Yêu cầu đã được gửi thành công!";

  @override
  String get sentRequestSuccessPrompt => "Chúng tôi rất vui thông báo rằng yêu cầu của bạn đã được gửi thành công. Chúng tôi sẽ xem xét nó và sớm phản hồi lại bạn. Cảm ơn bạn đã chọn chúng tôi để giải quyết nhu cầu của bạn.";

  @override
  String get pendingApproval => "Chờ duyệt";

  @override
  String get backToHomepage => "Quay lại trang chính";

  @override
  String get inputNoteCheckOut => "Lưu ý cho người bán ...";

  @override
  String warningVoucher(price, currencyName) => "Mua thêm ${simpleCurrency(price, name: currencyName)} sản phẩm để sử dụng Voucher";

  @override
  String get freeShip => "Miễn phí giao hàng";

  @override
  String socN(int count) {
    return "Soc ${compact(count)}";
  }

  @override
  String get dealOneUSD => "Deal 1\$";

  @override
  String get hotVoucher => "Hot Voucher";

  @override
  String get trending => "Đang thịnh hành";

  @override
  String get travelItems => "Dụng cụ du lịch";

  @override
  String get electronicInvoices => "Hóa đơn điện tử";

  @override
  String get desElectronicInvoices => "Soctrip chỉ phát hành hóa đơn điện tử";

  @override
  String get companyName => "Tên công ty";

  @override
  String get companyAddress => "Địa chỉ công ty";

  @override
  String get taxCode => "Mã số thuế";

  @override
  String get enterCompanyName => "Nhập tên công ty";

  @override
  String get enterCompanyAddress => "Nhập địa chỉ công ty";

  @override
  String get enterTaxCode => "Nhập mã thuế";

  @override
  String get firstName => "Tên";

  @override
  String get lastName => "Họ";

  @override
  String get addressLineOne => "Địa chỉ 1";

  @override
  String get addressLineTwo => "Địa chỉ 2";

  @override
  String get zipCode => "Zipcode";

  @override
  String get billingAddress => "Địa chỉ thanh toán";

  @override
  String get enterFirstName => "Nhập Tên";

  @override
  String get enterLastName => "Nhập Họ";

  @override
  String get enterZipcode => "Nhập zipcode";

  @override
  String get used => "Đã dùng";

  @override
  String get noShopVoucher => "Chưa có phiếu mua hàng nào";

  @override
  String get noShippingVoucher => "Chưa có phiếu miễn phí vận chuyển";

  @override
  String get shipment => "Đơn vị vận chuyển";

  @override
  String get descriptionNoVoucher => "Vui lòng nhập bất kỳ mã voucher hợp lệ nào vào thanh nhập được cung cấp ở trên";

  @override
  String get errorNoShipmentMethodAvailable =>
      "Lỗi: Không có phương thức vận chuyển nào sẵn có để giao hàng từ vị trí của shop đến vị trí của bạn";

  String get addressLine1 => "Địa chỉ 1";

  @override
  String get addressLine2 => "Địa chỉ 2 (không bắt buộc)";

  @override
  String get selectCountries => "Chọn quốc gia";

  @override
  String get selectProvince => "Chọn tỉnh";

  @override
  String get selectDistrict => "Chọn huyện";

  @override
  String get stateProvince => "Tiểu bang/Tỉnh";

  @override
  String get pleaseSelectShipment => "Vui lòng chọn đơn vị vận chuyển";

  @override
  String get categories => "Danh mục";

  @override
  String get selectCategory => "Chọn danh mục";

  @override
  String get detailedInformation => "Thông tin chi tiết";

  @override
  String get voucherDisplayApplicabeProduct => "Hiển thị voucher & sản phẩm áp dụng";

  @override
  String get applyForArea => "Khu vực";

  @override
  String get selectArea => "Chọn khu vực";

  @override
  String get enableExportElectronicInvoices => "Cho phép người mua xuất hóa đơn điện tử";

  @override
  String get waitingApproveUpdateShop => "Yêu cầu của bạn đang chờ phê duyệt";

  @override
  String get waitingApproveUpdateShopPrompt => "Cửa hàng của bạn hiện đang được nhóm của chúng tôi xem xét. Chúng tôi đang nỗ lực để đảm bảo cửa hàng đáp ứng các tiêu chuẩn của chúng tôi. Chúng tôi sẽ thông báo cho bạn sau khi cửa hàng được phê duyệt và sẵn sàng hoạt động. Cảm ơn vì sự kiên nhẫn của bạn.";

  @override
  String get updateShop => "Cập nhật cửa hàng";

  @override
  String get requestOpenRestaurant => "Yêu cầu mở nhà hàng";

  @override
  String get restaurantInfo => "Thông tin nhà hàng";

  @override
  String get restaurantInfoPrompt => "Vui lòng nhập thông tin nhà hàng. Tất cả các trường đều bắt buộc.";

  @override
  String get missBasicInformation => "Vui lòng kiểm tra lại thông tin của Thông tin cơ bản";

  @override
  String get missCategory => "Vui lòng chọn danh mục cho voucher";

  @override
  String get missDetailInformation => "Vui lòng kiểm tra lại thông tin của Thông tin chi tiết";

  @override
  String get missProduct => "Vui lòng chọn sản phẩm cho voucher";

  @override
  String get missValidPeriod => "Vui lòng kiểm tra lại thông tin của thời gian hiệu lực";

  @override
  String get missVoucherSetting => "Vui lòng kiểm tra lại thông tin của Thiết lập voucher";

  @override
  String get dob_1 => "Tháng 1";
  @override
  String get dob_2 => "Tháng 2";
  @override
  String get dob_3 => "Tháng 3";
  @override
  String get dob_4 => "Tháng 4";
  @override
  String get dob_5 => "Tháng 5";
  @override
  String get dob_6 => "Tháng 6";
  @override
  String get dob_7 => "Tháng 7";
  @override
  String get dob_8 => "Tháng 8";
  @override
  String get dob_9 => "Tháng 9";
  @override
  String get dob_10 => "Tháng 10";
  @override
  String get dob_11 => "Tháng 11";
  @override
  String get dob_12 => "Tháng 12";
  @override
  String get selectStartDate => "Chọn ngày bắt đầu";
  @override
  String get selectEndDate => "Chọn ngày kết thúc";

  @override
  String get megaMenu => "Mega Menu";

  @override
  String get center => "Center";

  @override
  String get social => "Mạng xã hội";

  @override
  String get shop => "Cửa hàng";

  @override
  String get restaurant => "Nhà hàng";

  @override
  String get travelTour => "Tour du lịch";

  @override
  String get notDeleteAddressDefault => "Không thể xóa địa chỉ mặc định";

  @override
  String get deliveryDiscount => "Giảm giá vận chuyển";

  @override
  String get requestToOpenRestaurant => "Yêu cầu để mở cửa hàng";

  @override
  String get updateRestaurant => "Cập nhật cửa hàng";

  @override
  String get emptyCart => "Giỏ của bạn trống";

  @override
  String get chooseShipment => "Chọn đơn vị vận chuyển";

  @override
  String get descriptionEmptyCart => "Giỏ hàng của bạn đang chờ bạn. Thêm một số mặt hàng để \nhoàn tất giao dịch mua hàng của bạn.";

  @override
  String get unlimited => "Không giới hạn";

  @override
  String get terrible => "Kinh khủng";

  @override
  String get poor => "Bần";

  @override
  String get fair => "Tệ";

  @override
  String get amazing => "Tuyệt vời";
}
