name: shared_module
description: A new Flutter package project.
version: 0.0.1
homepage: https://tma.com.vn

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_bloc: any
  go_router: any
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  scrollable_positioned_list: ^0.3.8
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  cross_file: ^0.3.3+4
  carousel_slider: ^4.2.1
  slide_countdown: ^0.6.0
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  location: ^5.0.0
  intl_phone_field: ^3.2.0
  flutter_html: 3.0.0-beta.2
  bloc: ^8.1.2
  number_paginator: ^0.3.2
  flutter_staggered_grid_view: ^0.6.2
  firebase_messaging: ^14.6.7
  soctrip_icons:
    path: ../soctrip-icon
  bloom_filter:
    path: ../bloom-filter
  file_picker: ^5.5.0
  # stripe payment
  flutter_stripe: ^9.4.0
  async_locks: ^3.3.2
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  awesome_dialog: ^3.1.0
  numberpicker: ^2.1.2
  quiver: ^3.2.1
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2
  chewie: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/menu-icons/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
